# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # And much more! For more information, visit the docs: https://espanso.org/docs/
  - trigger: "ttt"
    replace: "{{current_time}} - "
    vars:
      - name: current_time
        type: date
        params:
          format: "%H:%M"

  - trigger: "dt;"
    replace: "## {{date_time}}"
    vars:
      - name: date_time
        type: date
        params:
          format: "%Y-%m-%d %a\n\n%H:%M - "
  - trigger: cc;
    replace: clear && clear
#    force_mode: clipboard
  - trigger: id;
    replace: pnpm install && pnpm dev
    force_mode: clipboard
  - trigger: ib;
    replace: pnpm install && pnpm build
    force_mode: clipboard
  - trigger: ibp;
    replace: pnpm install && pnpm build && pnpm preview
    force_mode: clipboard
  - regex: \bd;
    replace: "pnpm dev"
  - trigger: i;
    replace: "pnpm install"
  - trigger: b;
    replace: "pnpm build"
  - trigger: "bp;"
    replace: "pnpm build && pnpm preview"
    force_mode: clipboard
  - trigger: bw;
    replace: "pnpm build --watch"
  - trigger: gp;
    replace: "git pull"
  - trigger: gc;
    replace: "git checkout "
  - trigger: gc-
    replace: "git checkout -"
  - trigger: "gm;"
    replace: "git checkout main && git pull"
    force_mode: clipboard
  - trigger: "gcm;"
    replace: "git checkout main && git pull"
    force_mode: clipboard
  - trigger: "gr;"
    replace: "git rebase origin/main"
    force_mode: clipboard
  - trigger: "grm;"
    replace: "git rebase origin/main"
    force_mode: clipboard
  - trigger: gb;
    replace: "git checkout -b "
  - trigger: gl;
    replace: "git log --oneline "
  - trigger: gwl
    replace: "git worktree list"
  - trigger: gwr
    replace: "git worktree remove"
  - regex: \bp;
    replace: "clear && npx playwright test --project=chromium "
  - regex: \bv;
    replace: "clear &&  npx vitest "
    force_mode: clipboard
  - trigger: vp;
    replace: "clear &&  npx vitest {{clipboard}}"
    force_mode: clipboard
    vars:
      - name: "clipboard"
        type: "clipboard"
  - trigger: vr;
    replace: "clear &&  npx vitest run "
  - trigger: br;
    replace: "border:solid red 5px;"
  #  delay: 50
  - trigger: cl;
    replace: 'console.log("{{clipb}}", {{clipb}});'
    vars:
      - name: "clipb"
        type: "clipboard"
  # Emojis

  - trigger: srg;
    replace: ¯\_(ツ)_/¯
  - trigger: fp;
    replace: "🤦‍♂️"
  - trigger: "gc:"
    replace: "✅"
  - trigger: ki;
    replace: "😘"
  - trigger: ha;
    replace: "😂"
  - trigger: pd;
    replace: "👇"
  - trigger: pl;
    replace: "👈"
  - trigger: pr;
    replace: "👉 "
  - trigger: pu;
    replace: "👆"
  - trigger: ay;
    replace: "🙏"
  - trigger: ?;
    replace: "❓"
  - trigger: hh;
    replace: "🤣"
  - trigger: see;
    replace: "🙈"
  - trigger: sn;
    replace: "😆"
  - trigger: sw;
    replace: "😅"
  - trigger: ta;
    replace: "🎉"
  - trigger: th;
    replace: "🤔"
  - trigger: tu;
    replace: "👍"
  - trigger: ua;
    replace: "😒"
  - trigger: wa;
    replace: "👋"
  - trigger: wi;
    replace: "😉"
  - regex: \bx;
    replace: "❌"

  - trigger: ":quote"
    replace: "{{output}}"
    vars:
      - name: output
        type: choice
        params:
          values:
            - "Every moment is a fresh beginning."
            - "Everything you can imagine is real."
            - "Whatever you do, do it well."
